// <auto-generated />
using System;
using CalorieTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CalorieTracker.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260519131535_BugFixDetailedMealTable")]
    partial class BugFixDetailedMealTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CalorieTracker.Models.DetailedFood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("FoodGroupId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FoodId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SearchKeywords")
                        .IsRequired()
                        .HasColumnType("LONGTEXT");

                    b.HasKey("Id");

                    b.HasIndex("FoodId")
                        .IsUnique();

                    b.HasIndex("FoodName")
                        .IsUnique();

                    b.ToTable("DetailedFoods");
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedMeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DetailedMealPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DetailedMealPlanId");

                    b.ToTable("DetailedMeals");
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedMealComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DetailedFoodId")
                        .HasColumnType("int");

                    b.Property<int>("DetailedMealId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("DetailedFoodId");

                    b.HasIndex("DetailedMealId");

                    b.ToTable("DetailedMealComponents");
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedMealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DetailedMealPlans");
                });

            modelBuilder.Entity("CalorieTracker.Models.FoodConstituent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DetailedFoodId")
                        .HasColumnType("int");

                    b.Property<string>("NutrientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Quantity")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("DetailedFoodId");

                    b.HasIndex("NutrientId");

                    b.ToTable("FoodConstituents");
                });

            modelBuilder.Entity("CalorieTracker.Models.FoodSummarySql", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Calories")
                        .HasColumnType("double");

                    b.Property<double?>("Carbohydrates")
                        .IsRequired()
                        .HasColumnType("double");

                    b.Property<double?>("Fat")
                        .IsRequired()
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Protein")
                        .IsRequired()
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Foods");
                });

            modelBuilder.Entity("CalorieTracker.Models.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("FoodId")
                        .HasColumnType("int");

                    b.Property<int>("MealNameId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealNameId");

                    b.ToTable("Meals");
                });

            modelBuilder.Entity("CalorieTracker.Models.MealName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("MealPlanId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealPlanId");

                    b.HasIndex("UserId");

                    b.ToTable("MealNames");
                });

            modelBuilder.Entity("CalorieTracker.Models.MealPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("MealPlans");
                });

            modelBuilder.Entity("CalorieTracker.Models.Nutrient", b =>
                {
                    b.Property<string>("NutrientId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("DefaultUnit")
                        .HasColumnType("longtext");

                    b.Property<string>("NutrientName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("NutrientId");

                    b.ToTable("Nutrients");
                });

            modelBuilder.Entity("CalorieTracker.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedFood", b =>
                {
                    b.OwnsOne("CalorieTracker.Models.DbCalories", "Calories", b1 =>
                        {
                            b1.Property<int>("DetailedFoodId")
                                .HasColumnType("int");

                            b1.Property<int?>("Quantity")
                                .HasColumnType("int");

                            b1.Property<string>("Unit")
                                .HasColumnType("longtext");

                            b1.HasKey("DetailedFoodId");

                            b1.ToTable("DetailedFoods");

                            b1.WithOwner()
                                .HasForeignKey("DetailedFoodId");
                        });

                    b.OwnsOne("CalorieTracker.Models.DbEnergy", "Energy", b1 =>
                        {
                            b1.Property<int>("DetailedFoodId")
                                .HasColumnType("int");

                            b1.Property<double?>("Quantity")
                                .HasColumnType("double");

                            b1.Property<string>("Unit")
                                .HasColumnType("longtext");

                            b1.HasKey("DetailedFoodId");

                            b1.ToTable("DetailedFoods");

                            b1.WithOwner()
                                .HasForeignKey("DetailedFoodId");
                        });

                    b.Navigation("Calories");

                    b.Navigation("Energy");
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedMeal", b =>
                {
                    b.HasOne("CalorieTracker.Models.DetailedMealPlan", null)
                        .WithMany("DetailedMeals")
                        .HasForeignKey("DetailedMealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedMealComponent", b =>
                {
                    b.HasOne("CalorieTracker.Models.DetailedFood", "DetailedFood")
                        .WithMany()
                        .HasForeignKey("DetailedFoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Models.DetailedMeal", null)
                        .WithMany("Components")
                        .HasForeignKey("DetailedMealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailedFood");
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedMealPlan", b =>
                {
                    b.HasOne("CalorieTracker.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.FoodConstituent", b =>
                {
                    b.HasOne("CalorieTracker.Models.DetailedFood", "Food")
                        .WithMany()
                        .HasForeignKey("DetailedFoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Models.Nutrient", "Nutrient")
                        .WithMany()
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("CalorieTracker.Models.Meal", b =>
                {
                    b.HasOne("CalorieTracker.Models.FoodSummarySql", "Food")
                        .WithMany("Meals")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Models.MealName", "MealName")
                        .WithMany("Meals")
                        .HasForeignKey("MealNameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("MealName");
                });

            modelBuilder.Entity("CalorieTracker.Models.MealName", b =>
                {
                    b.HasOne("CalorieTracker.Models.MealPlan", "MealPlan")
                        .WithMany("MealNames")
                        .HasForeignKey("MealPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalorieTracker.Models.User", "User")
                        .WithMany("MealNames")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MealPlan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.MealPlan", b =>
                {
                    b.HasOne("CalorieTracker.Models.User", "User")
                        .WithMany("MealPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedMeal", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("CalorieTracker.Models.DetailedMealPlan", b =>
                {
                    b.Navigation("DetailedMeals");
                });

            modelBuilder.Entity("CalorieTracker.Models.FoodSummarySql", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("CalorieTracker.Models.MealName", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("CalorieTracker.Models.MealPlan", b =>
                {
                    b.Navigation("MealNames");
                });

            modelBuilder.Entity("CalorieTracker.Models.User", b =>
                {
                    b.Navigation("MealNames");

                    b.Navigation("MealPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
